// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-dMTJalsipvuXEzJ9URs4PDbO-D0tuP0',
    appId: '1:220180521564:android:3b4707b99140696ab8fc99',
    messagingSenderId: '220180521564',
    projectId: 'advertising-app-597a6',
    databaseURL: 'https://advertising-app-597a6-default-rtdb.firebaseio.com',
    storageBucket: 'advertising-app-597a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLwzd0lhiZFYcvepUdgvr33lwFoSe3l4',
    appId: '1:220180521564:ios:3fe311b78121766bb8fc99',
    messagingSenderId: '220180521564',
    projectId: 'advertising-app-597a6',
    databaseURL: 'https://advertising-app-597a6-default-rtdb.firebaseio.com',
    storageBucket: 'advertising-app-597a6.appspot.com',
    androidClientId: '220180521564-4ne28lhbe8ih6btmv2436stu3m45v4ku.apps.googleusercontent.com',
    iosClientId: '220180521564-mdk7q7scrco75d4rhovaobhdcl1lico3.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminmyecommerceapp',
  );
}
